site_name: Annotation automatique des maladies du manioc et images africaines
theme:
  name: material
nav:
  - Accueil: index.md
  - Méthodologie: methodologie.md
  - Installation: installation.md
  - data: data.md
  - Apk: apk.md
  - Conclusion: conclusion.md
  - Contact: contact.md
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - codehilite:
      guess_lang: false
  - footnotes
  - attr_list
  - def_list
  - tables
  - md_in_html

